#if !canImport(ObjectiveC)
import XCTest

extension HttpPipelineHtmlSupportTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HttpPipelineHtmlSupportTests = [
        ("testResponse", testResponse),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(HttpPipelineHtmlSupportTests.__allTests__HttpPipelineHtmlSupportTests),
    ]
}
#endif
