#if !canImport(ObjectiveC)
import XCTest

extension UrlFormDecoderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UrlFormDecoderTests = [
        ("testBools", testBools),
        ("testBrackets", testBrackets),
        ("testBracketsWithIndices", testBracketsWithIndices),
        ("testDataDecodingWithBase64", testDataDecodingWithBase64),
        ("testDateDecodingWithIso8601", testDateDecodingWithIso8601),
        ("testDateDecodingWithMillisecondsSince1970", testDateDecodingWithMillisecondsSince1970),
        ("testDateDecodingWithSecondsSince1970", testDateDecodingWithSecondsSince1970),
        ("testDefaultStrategyAccumulatePairs", testDefaultStrategyAccumulatePairs),
        ("testOptionality", testOptionality),
        ("testPlusses", testPlusses),
    ]
}

extension UrlFormEncoderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UrlFormEncoderTests = [
        ("testEncoding_DeepObject", testEncoding_DeepObject),
        ("testEncoding_DoubleArray", testEncoding_DoubleArray),
        ("testEncoding_Emtpy", testEncoding_Emtpy),
        ("testEncoding_RootArray_SimpleObjects", testEncoding_RootArray_SimpleObjects),
        ("testEncodingCodable", testEncodingCodable),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(UrlFormDecoderTests.__allTests__UrlFormDecoderTests),
        testCase(UrlFormEncoderTests.__allTests__UrlFormEncoderTests),
    ]
}
#endif
