#if !canImport(ObjectiveC)
import XCTest

extension ResetTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ResetTests = [
        ("testResetCompact", testResetCompact),
        ("testResetPretty", testResetPretty),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ResetTests.__allTests__ResetTests),
    ]
}
#endif
