#if !canImport(ObjectiveC)
import XCTest

extension ApplicativeRouterHttpPipelineSupportTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ApplicativeRouterHttpPipelineSupportTests = [
        ("testRoute", testRoute),
        ("testRoute_UnrecognizedWithCustomNotFound", testRoute_UnrecognizedWithCustomNotFound),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ApplicativeRouterHttpPipelineSupportTests.__allTests__ApplicativeRouterHttpPipelineSupportTests),
    ]
}
#endif
