#if !canImport(ObjectiveC)
import XCTest

extension PlainTextTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PlainTextTests = [
        ("testPlainText", testPlainText),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(PlainTextTests.__allTests__PlainTextTests),
    ]
}
#endif
