#if !canImport(ObjectiveC)
import XCTest

extension SupportTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SupportTests = [
        ("testStyleAttribute", testStyleAttribute),
        ("testStyleElement", testStyleElement),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SupportTests.__allTests__SupportTests),
    ]
}
#endif
