version: 2

jobs:
  build:
    macos:
      xcode: "11.0.0"

    steps:
      - checkout

      - run:
          name: Mac Info
          command: system_profiler SPSoftwareDataType

      - run:
          name: Print Devices
          command: instruments -s devices

      - run:
          name: Run Swift tests
          command: make test-swift
          environment:
            SNAPSHOT_ARTIFACTS: $CIRCLE_ARTIFACTS
