#if !canImport(ObjectiveC)
import XCTest

extension SyntaxRouterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SyntaxRouterTests = [
        ("testAbsoluteString", testAbsoluteString),
        ("testCodableFormDataPostBody", testCodableFormDataPostBody),
        ("testHome", testHome),
        ("testLitFails", testLitFails),
        ("testPathComponents_IntParam", testPathComponents_IntParam),
        ("testPathComponents_StringParam", testPathComponents_StringParam),
        ("testPostBodyField", testPostBodyField),
        ("testPostBodyJsonDecodable", testPostBodyJsonDecodable),
        ("testRedirect", testRedirect),
        ("testRequest_WithBaseUrl", testRequest_WithBaseUrl),
        ("testRoot", testRoot),
        ("testSimpleQueryParams", testSimpleQueryParams),
        ("testSimpleQueryParams_SomeMissing", testSimpleQueryParams_SomeMissing),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SyntaxRouterTests.__allTests__SyntaxRouterTests),
    ]
}
#endif
