#if !canImport(ObjectiveC)
import XCTest

extension BackgroundTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BackgroundTests = [
        ("testBackground_RGBA", testBackground_RGBA),
    ]
}

extension BorderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BorderTests = [
        ("testBorders", testBorders),
    ]
}

extension CssRenderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CssRenderTests = [
        ("testAllOperatorsTogether", testAllOperatorsTogether),
        ("testASD", testASD),
        ("testClipRect", testClipRect),
        ("testFontInherit", testFontInherit),
        ("testMargins", testMargins),
        ("testNestedIds", testNestedIds),
        ("testRenderAfterContent", testRenderAfterContent),
        ("testRenderBoxSizing", testRenderBoxSizing),
        ("testRenderSelector_Adjacent", testRenderSelector_Adjacent),
        ("testRenderSelector_AdjacentOperator", testRenderSelector_AdjacentOperator),
        ("testRenderSelector_Attr", testRenderSelector_Attr),
        ("testRenderSelector_AttributeBeginsOperator", testRenderSelector_AttributeBeginsOperator),
        ("testRenderSelector_AttributeContainsOperator", testRenderSelector_AttributeContainsOperator),
        ("testRenderSelector_AttributeEndsOperator", testRenderSelector_AttributeEndsOperator),
        ("testRenderSelector_AttributeHyphenOperator", testRenderSelector_AttributeHyphenOperator),
        ("testRenderSelector_AttributeSpaceOperator", testRenderSelector_AttributeSpaceOperator),
        ("testRenderSelector_AttributeValOperator", testRenderSelector_AttributeValOperator),
        ("testRenderSelector_Child", testRenderSelector_Child),
        ("testRenderSelector_ChildOperator", testRenderSelector_ChildOperator),
        ("testRenderSelector_Class", testRenderSelector_Class),
        ("testRenderSelector_Combined", testRenderSelector_Combined),
        ("testRenderSelector_CombinedOperator", testRenderSelector_CombinedOperator),
        ("testRenderSelector_Deep", testRenderSelector_Deep),
        ("testRenderSelector_DeepOperator", testRenderSelector_DeepOperator),
        ("testRenderSelector_Elem", testRenderSelector_Elem),
        ("testRenderSelector_Id", testRenderSelector_Id),
        ("testRenderSelector_NestedCss", testRenderSelector_NestedCss),
        ("testRenderSelector_PseudoClass", testRenderSelector_PseudoClass),
        ("testRenderSelector_PseudoElem", testRenderSelector_PseudoElem),
        ("testRenderSelector_Sibling", testRenderSelector_Sibling),
        ("testRenderSelector_SiblingOperator", testRenderSelector_SiblingOperator),
        ("testRenderSelector_StandardCombinationOfElemIdClassPseudo", testRenderSelector_StandardCombinationOfElemIdClassPseudo),
        ("testRenderSelector_Star", testRenderSelector_Star),
        ("testRenderSelector_Union", testRenderSelector_Union),
        ("testRenderSelector_UnionOperator", testRenderSelector_UnionOperator),
        ("testRenderSelector_UsingStringLiterals", testRenderSelector_UsingStringLiterals),
        ("testSubCss", testSubCss),
    ]
}

extension FlexBoxTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FlexBoxTests = [
        ("testFlexBox", testFlexBox),
    ]
}

extension FullStylesheetTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FullStylesheetTests = [
        ("testABigStyleSheet", testABigStyleSheet),
    ]
}

extension MediaTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MediaTests = [
        ("testMediaQueryNot", testMediaQueryNot),
        ("testMediaQueryOnly", testMediaQueryOnly),
    ]
}

extension PropertyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PropertyTests = [
        ("testPrefixed_Monoid", testPrefixed_Monoid),
    ]
}

extension SizeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SizeTests = [
        ("testCalc", testCalc),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BackgroundTests.__allTests__BackgroundTests),
        testCase(BorderTests.__allTests__BorderTests),
        testCase(CssRenderTests.__allTests__CssRenderTests),
        testCase(FlexBoxTests.__allTests__FlexBoxTests),
        testCase(FullStylesheetTests.__allTests__FullStylesheetTests),
        testCase(MediaTests.__allTests__MediaTests),
        testCase(PropertyTests.__allTests__PropertyTests),
        testCase(SizeTests.__allTests__SizeTests),
    ]
}
#endif
